package com.examportal.mail;

import com.examportal.common.FeatureDisabledException;
import com.examportal.config.FeatureFlags;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

/**
 * EmailService - Email delivery of result reports.
 *
 * PURPOSE: Sends result PDF to the student's registered email.
 *   - Attaches PDF generated by ReportService
 *   - HTML body with score summary
 *   - Configurable via spring.mail.* in application.yml
 *
 * STATUS: STRUCTURE DEFINED, IMPLEMENTATION COMMENTED OUT
 * FEATURE FLAG: features.email=true in application.yml
 *
 * TO ENABLE:
 *   1. Set features.email=true
 *   2. Set features.pdf=true (email requires PDF)
 *   3. Configure spring.mail.* with valid SMTP credentials
 *   4. Uncomment the implementation block below
 */
@Service
@RequiredArgsConstructor
public class EmailService {

    private final FeatureFlags featureFlags;

    public void sendResultEmail(Long attemptId, String recipientEmail) {
        if (!featureFlags.isEmail()) throw new FeatureDisabledException("email");

        // ================================================================
        // EMAIL IMPLEMENTATION - UNCOMMENT AFTER CONFIGURING SMTP
        // ================================================================
        //
        // // Step 1: Generate PDF attachment
        // byte[] pdfBytes = reportService.generateResultPdf(attemptId);
        //
        // // Step 2: Load result for email body
        // EvaluationResult result = evaluationRepository.findByAttemptId(attemptId)
        //     .orElseThrow(() -> new IllegalArgumentException("Result not found"));
        //
        // // Step 3: Build MIME message
        // MimeMessage message = mailSender.createMimeMessage();
        // MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");
        // helper.setTo(recipientEmail);
        // helper.setSubject("Your Examination Result - Score: " + result.getTotalScore());
        //
        // // Step 4: HTML body
        // String html = "<html><body>"
        //     + "<h2>Examination Result</h2>"
        //     + "<p>Total Score: <strong>" + result.getTotalScore() + "</strong></p>"
        //     + "<p>Correct: " + result.getCorrect() + " | "
        //     + "Wrong: " + result.getWrong() + " | "
        //     + "Unattempted: " + result.getUnattempted() + "</p>"
        //     + "<p>Please find your detailed result report attached.</p>"
        //     + "</body></html>";
        // helper.setText(html, true);
        //
        // // Step 5: Attach PDF
        // helper.addAttachment("exam_result.pdf",
        //     new ByteArrayResource(pdfBytes), MediaType.APPLICATION_PDF_VALUE);
        //
        // // Step 6: Send
        // mailSender.send(message);
        //
        // ================================================================

        throw new FeatureDisabledException("email");
    }
}
